version: "3.9"

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis_server
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "StrongPassword123!"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "StrongPassword123!", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    environment:
      - RITRUSTED_ORIGINS=http://localhost:5540
      - REDISINSIGHT_REDIS_URI=redis://:StrongPassword123!@redis:6379
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
    driver: local
